name: Test CI/CD Security Tools

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set script as executable
        run: chmod +x ./simulated-malicious.sh

      - name: Run simulated malicious script
        run: ./simulated-malicious.sh
